import 'package:flutter/material.dart';

void main() {
  runApp(const FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          1(),
        ]),
      ),
    );
  }
}

class 1 extends StatelessWidget {
@override
Widget build(BuildContext context) {
return Column(
children: [
Container(
width: 402,
height: 874,
decoration: ShapeDecoration(
color: const Color(0xFFF1F1F1),
shape: RoundedRectangleBorder(
borderRadius: BorderRadius.circular(50),
),
),
child: Stack(
children: [
Positioned(
left: -24,
top: -23,
child: Container(
width: 450,
height: 920,
decoration: BoxDecoration(
image: DecorationImage(
image: NetworkImage("https://placehold.co/450x920"),
fit: BoxFit.cover,
),
),
),
),
Positioned(
left: 0,
top: 0,
child: Container(
width: 402,
height: 874,
clipBehavior: Clip.antiAlias,
decoration: BoxDecoration(),
child: Stack(
children: [
Positioned(
left: 0,
top: 344,
child: Container(
width: 402,
height: 530,
clipBehavior: Clip.antiAlias,
decoration: BoxDecoration(),
child: Stack(
children: [
Positioned(
left: 14,
top: 16,
child: Container(
width: 372,
height: 94,
clipBehavior: Clip.antiAlias,
decoration: BoxDecoration(),
child: Stack(
children: [
Positioned(
left: 2,
top: 0,
child: Container(
width: 174,
height: 94,
child: Stack(
children: [
Positioned(
left: 0,
top: 30,
child: SizedBox(
width: 174,
height: 34,
child: Text(
'취미',
textAlign: TextAlign.center,
style: TextStyle(
color: Colors.white,
fontSize: 24,
fontFamily: 'Inter',
fontWeight: FontWeight.w700,
),
),
),
),
],
),
),
),
Positioned(
left: 198,
top: 0,
child: Container(
width: 174,
height: 94,
child: Stack(
children: [
Positioned(
left: 0,
top: 0,
child: Container(
width: 174,
height: 94,
decoration: ShapeDecoration(
color: const Color(0xFFDAD3E8),
shape: RoundedRectangleBorder(
borderRadius: BorderRadius.circular(30),
),
),
),
),
Positioned(
left: 0,
top: 30,
child: SizedBox(
width: 174,
height: 34,
child: Text(
'취업',
textAlign: TextAlign.center,
style: TextStyle(
color: Colors.white,
fontSize: 24,
fontFamily: 'Inter',
fontWeight: FontWeight.w700,
),
),
),
),
],
),
),
),
],
),
),
),
Positioned(
left: 14,
top: 126,
child: Container(
width: 372,
height: 94,
clipBehavior: Clip.antiAlias,
decoration: BoxDecoration(),
child: Stack(
children: [
Positioned(
left: 2,
top: 0,
child: Container(
width: 174,
height: 94,
child: Stack(
children: [
Positioned(
left: 0,
top: 0,
child: Container(
width: 174,
height: 94,
decoration: ShapeDecoration(
color: const Color(0xFFDAD3E8),
shape: RoundedRectangleBorder(
borderRadius: BorderRadius.circular(30),
),
),
),
),
Positioned(
left: 0,
top: 30,
child: SizedBox(
width: 174,
height: 34,
child: Text(
'창업',
textAlign: TextAlign.center,
style: TextStyle(
color: Colors.white,
fontSize: 24,
fontFamily: 'Inter',
fontWeight: FontWeight.w700,
),
),
),
),
],
),
),
),
Positioned(
left: 198,
top: 0,
child: Container(
width: 174,
height: 94,
child: Stack(
children: [
Positioned(
left: 0,
top: 0,
child: Container(
width: 174,
height: 94,
decoration: ShapeDecoration(
color: const Color(0xFFDAD3E8),
shape: RoundedRectangleBorder(
borderRadius: BorderRadius.circular(30),
),
),
),
),
Positioned(
left: 0,
top: 30,
child: SizedBox(
width: 174,
height: 34,
child: Text(
'멘토 만남',
textAlign: TextAlign.center,
style: TextStyle(
color: Colors.white,
fontSize: 24,
fontFamily: 'Inter',
fontWeight: FontWeight.w700,
),
),
),
),
],
),
),
),
],
),
),
),
Positioned(
left: 14,
top: 236,
child: Container(
width: 372,
height: 94,
clipBehavior: Clip.antiAlias,
decoration: BoxDecoration(),
child: Stack(
children: [
Positioned(
left: 2,
top: 0,
child: Container(
width: 174,
height: 94,
child: Stack(
children: [
Positioned(
left: 0,
top: 0,
child: Container(
width: 174,
height: 94,
decoration: ShapeDecoration(
color: const Color(0xFFDAD3E8),
shape: RoundedRectangleBorder(
borderRadius: BorderRadius.circular(30),
),
),
),
),
Positioned(
left: 0,
top: 30,
child: SizedBox(
width: 174,
height: 34,
child: Text(
'기타',
textAlign: TextAlign.center,
style: TextStyle(
color: Colors.white,
fontSize: 24,
fontFamily: 'Inter',
fontWeight: FontWeight.w700,
),
),
),
),
],
),
),
),
],
),
),
),
Positioned(
left: 9,
top: 346,
child: Container(
width: 383,
height: 94,
clipBehavior: Clip.antiAlias,
decoration: BoxDecoration(),
child: Stack(
children: [
Positioned(
left: 0,
top: 0,
child: Container(width: 383, height: 94),
),
],
),
),
),
],
),
),
),
Positioned(
left: 0,
top: 202,
child: Container(
width: 402,
height: 142,
clipBehavior: Clip.antiAlias,
decoration: BoxDecoration(),
child: Stack(
children: [
Positioned(
left: 11,
top: 10,
child: SizedBox(
width: 381,
height: 89,
child: Text(
'전통 기술을 배우고 \n싶은 이유는 무엇인가요?',
textAlign: TextAlign.center,
style: TextStyle(
color: Colors.black,
fontSize: 30,
fontFamily: 'Inter',
fontWeight: FontWeight.w700,
),
),
),
),
Positioned(
left: 13,
top: 107,
child: SizedBox(
width: 379,
height: 25,
child: Text(
'목표에 맞는 맞춤 추천을 제공해요!',
textAlign: TextAlign.center,
style: TextStyle(
color: const Color(0xFF868282),
fontSize: 16,
fontFamily: 'Inter',
fontWeight: FontWeight.w700,
),
),
),
),
],
),
),
),
Positioned(
left: 0,
top: 130,
child: Opacity(
opacity: 0.70,
child: Container(
width: 402,
height: 66,
clipBehavior: Clip.antiAlias,
decoration: BoxDecoration(
color: Colors.white,
boxShadow: [
BoxShadow(
color: Color(0x3F000000),
blurRadius: 4,
offset: Offset(0, 4),
spreadRadius: 3,
)
],
),
child: Stack(
children: [
Positioned(
left: 10,
top: 9,
child: SizedBox(
width: 381,
height: 48,
child: Text(
'20% 진행중...',
textAlign: TextAlign.center,
style: TextStyle(
color: Colors.black,
fontSize: 18,
fontFamily: 'Inter',
fontWeight: FontWeight.w700,
),
),
),
),
],
),
),
),
),
Positioned(
left: 1,
top: 0,
child: Container(
width: 402,
height: 130,
clipBehavior: Clip.antiAlias,
decoration: BoxDecoration(),
child: Stack(
children: [
Positioned(
left: 162,
top: 91,
child: Text(
'성향 검사',
style: TextStyle(
color: Colors.black,
fontSize: 20,
fontFamily: 'Inter',
fontWeight: FontWeight.w700,
height: 1.10,
),
),
),
Positioned(
left: 31,
top: 85,
child: Container(width: 30, height: 30, child: Stack()),
),
Positioned(
left: 0,
top: 129,
child: Container(
width: 402,
decoration: ShapeDecoration(
shape: RoundedRectangleBorder(
side: BorderSide(
width: 1,
strokeAlign: BorderSide.strokeAlignCenter,
color: Colors.black.withValues(alpha: 0.30),
),
),
),
),
),
],
),
),
),
],
),
),
),
Positioned(
left: 91,
top: 764,
child: Container(
width: 221,
height: 48,
decoration: BoxDecoration(
boxShadow: [
BoxShadow(
color: Color(0x3F000000),
blurRadius: 4,
offset: Offset(0, 4),
spreadRadius: 0,
)
],
),
child: Stack(
children: [
Positioned(
left: 0,
top: 0,
child: Container(
width: 221,
height: 48,
decoration: ShapeDecoration(
color: const Color(0xFFD9D9D9),
shape: RoundedRectangleBorder(
borderRadius: BorderRadius.circular(30),
),
),
),
),
Positioned(
left: 82,
top: 13,
child: Text(
'다음으로',
style: TextStyle(
color: Colors.black,
fontSize: 15,
fontFamily: 'Inter',
fontWeight: FontWeight.w700,
height: 1.47,
),
),
),
],
),
),
),
],
),
),
],
);
}
}
